return [
	'#include <dirent.h>',
	'#include <errno.h>',
	'#include <fcntl.h>',
	'#include <poll.h>',
	'#include <signal.h>',
	'#include <stdio.h>',
	'#include <stdlib.h>',
	'#include <string.h>',
	'#include <sys/random.h>',
	'#include <sys/stat.h>',
	'#include <sys/types.h>',
	'#include <sys/wait.h>',
	'#include <unistd.h>',
];
