const errno	= {};

errno.EPERM			 	= 1;/* Operation not permitted */
errno.ENOENT		 	= 2;/* No such file or directory */
errno.ESRCH				= 3;/* No such process */
errno.EINTR				= 4;/* Interrupted system call */
errno.EIO				= 5;/* I/O error */
errno.ENXIO				= 6;/* No such device or address */
errno.E2BIG				= 7;/* Argument list too long */
errno.ENOEXEC		 	= 8;/* Exec format error */
errno.EBADF				= 9;/* Bad file number */
errno.ECHILD			= 10;/* No child processes */
errno.EAGAIN			= 11;/* Try again */
errno.ENOMEM			= 12;/* Out of memory */
errno.EACCES			= 13;/* Permission denied */
errno.EFAULT			= 14;/* Bad address */
errno.ENOTBLK			= 15;/* Block device required */
errno.EBUSY				= 16;/* Device or resource busy */
errno.EEXIST			= 17;/* File exists */
errno.EXDEV				= 18;/* Cross-device link */
errno.ENODEV			= 19;/* No such device */
errno.ENOTDIR			= 20;/* Not a directory */
errno.EISDIR			= 21;/* Is a directory */
errno.EINVAL			= 22;/* Invalid argument */
errno.ENFILE			= 23;/* File table overflow */
errno.EMFILE			= 24;/* Too many open files */
errno.ENOTTY			= 25;/* Not a typewriter */
errno.ETXTBSY			= 26;/* Text file busy */
errno.EFBIG				= 27;/* File too large */
errno.ENOSPC			= 28;/* No space left on device */
errno.ESPIPE			= 29;/* Illegal seek */
errno.EROFS				= 30;/* Read-only file system */
errno.EMLINK			= 31;/* Too many links */
errno.EPIPE				= 32;/* Broken pipe */
errno.EDOM				= 33;/* Math argument out of domain of func */
errno.ERANGE			= 34;/* Math result not representable */
errno.ADLK				= 35; /* Resource deadlock would occur */
errno.AMETOOLONG		= 36; /* File name too long */
errno.ENOLCK			= 37; /* No record locks available */
errno.ENOSYS			= 38; /* Invalid system call number */
errno.ENOTEMPTY			= 39; /* Directory not empty */
errno.ELOOP				= 40; /* Too many symbolic links encountered */
errno.ENOMSG			= 42; /* No message of desired type */
errno.EIDRM				= 43; /* Identifier removed */
errno.ECHRNG			= 44; /* Channel number out of range */
errno.EL2NSYNC			= 45; /* Level 2 not synchronized */
errno.EL3HLT			= 46; /* Level 3 halted */
errno.EL3RST			= 47; /* Level 3 reset */
errno.ELNRNG			= 48; /* Link number out of range */
errno.EUNATCH			= 49; /* Protocol driver not attached */
errno.ENOCSI			= 50; /* No CSI structure available */
errno.EL2HLT			= 51; /* Level 2 halted */
errno.EBADE				= 52; /* Invalid exchange */
errno.EBADR				= 53; /* Invalid request descriptor */
errno.EXFULL			= 54; /* Exchange full */
errno.ENOANO			= 55; /* No anode */
errno.EBADRQC			= 56; /* Invalid request code */
errno.EBADSLT			= 57; /* Invalid slot */
errno.EBFONT			= 59; /* Bad font file format */
errno.ENOSTR			= 60; /* Device not a stream */
errno.ENODATA			= 61; /* No data available */
errno.ETIME				= 62; /* Timer expired */
errno.ENOSR				= 63; /* Out of streams resources */
errno.ENONET			= 64; /* Machine is not on the network */
errno.ENOPKG			= 65; /* Package not installed */
errno.EREMOTE			= 66; /* Object is remote */
errno.ENOLINK			= 67; /* Link has been severed */
errno.EADV				= 68; /* Advertise error */
errno.ESRMNT			= 69; /* Srmount error */
errno.ECOMM				= 70; /* Communication error on send */
errno.EPROTO			= 71; /* Protocol error */
errno.EMULTIHOP			= 72; /* Multihop attempted */
errno.EDOTDOT			= 73; /* RFS specific error */
errno.EBADMSG			= 74; /* Not a data message */
errno.EOVERFLOW			= 75; /* Value too large for defined data type */
errno.ENOTUNIQ			= 76; /* Name not unique on network */
errno.EBADFD			= 77; /* File descriptor in bad state */
errno.EREMCHG			= 78; /* Remote address changed */
errno.ELIBACC			= 79; /* Can not access a needed shared library */
errno.ELIBBAD			= 80; /* Accessing a corrupted shared library */
errno.ELIBSCN			= 81; /* .lib section in a.out corrupted */
errno.ELIBMAX			= 82; /* Attempting to link in too many shared libraries */
errno.ELIBEXEC			= 83; /* Cannot exec a shared library directly */
errno.EILSEQ			= 84; /* Illegal byte sequence */
errno.ERESTART			= 85; /* Interrupted system call should be restarted */
errno.ESTRPIPE			= 86; /* Streams pipe error */
errno.EUSERS			= 87; /* Too many users */
errno.ENOTSOCK			= 88; /* Socket operation on non-socket */
errno.EDESTADDRREQ		= 89; /* Destination address required */
errno.EMSGSIZE			= 90; /* Message too long */
errno.EPROTOTYPE		= 91; /* Protocol wrong type for socket */
errno.ENOPROTOOPT		= 92; /* Protocol not available */
errno.EPROTONOSUPPORT	= 93; /* Protocol not supported */
errno.ESOCKTNOSUPPORT	= 94; /* Socket type not supported */
errno.EOPNOTSUPP		= 95; /* Operation not supported on transport endpoint */
errno.EPFNOSUPPORT		= 96; /* Protocol family not supported */
errno.EAFNOSUPPORT		= 97; /* Address family not supported by protocol */
errno.EADDRINUSE		= 98; /* Address already in use */
errno.EADDRNOTAVAIL		= 99; /* Cannot assign requested address */
errno.ENETDOWN			= 100; /* Network is down */
errno.ENETUNREACH		= 101; /* Network is unreachable */
errno.ENETRESET			= 102; /* Network dropped connection because of reset */
errno.ECONNABORTED		= 103; /* Software caused connection abort */
errno.ECONNRESET		= 104; /* Connection reset by peer */
errno.ENOBUFS			= 105; /* No buffer space available */
errno.EISCONN			= 106; /* Transport endpoint is already connected */
errno.ENOTCONN			= 107; /* Transport endpoint is not connected */
errno.ESHUTDOWN			= 108; /* Cannot send after transport endpoint shutdown */
errno.ETOOMANYREFS		= 109; /* Too many references: cannot splice */
errno.ETIMEDOUT			= 110; /* Connection timed out */
errno.ECONNREFUSED		= 111; /* Connection refused */
errno.EHOSTDOWN			= 112; /* Host is down */
errno.EHOSTUNREACH		= 113; /* No route to host */
errno.EALREADY			= 114; /* Operation already in progress */
errno.EINPROGRESS		= 115; /* Operation now in progress */
errno.ESTALE			= 116; /* Stale file handle */
errno.EUCLEAN			= 117; /* Structure needs cleaning */
errno.ENOTNAM			= 118; /* Not a XENIX named type file */
errno.ENAVAIL			= 119; /* No XENIX semaphores available */
errno.EISNAM			= 120; /* Is a named type file */
errno.EREMOTEIO			= 121; /* Remote I/O error */
errno.EDQUOT			= 122; /* Quota exceeded */
errno.ENOMEDIUM			= 123; /* No medium found */
errno.EMEDIUMTYPE		= 124; /* Wrong medium type */
errno.ECANCELED			= 125; /* Operation Canceled */
errno.ENOKEY			= 126; /* Required key not available */
errno.EKEYEXPIRED		= 127; /* Key has expired */
errno.EKEYREVOKED		= 128; /* Key has been revoked */
errno.EKEYREJECTED		= 129; /* Key was rejected by service */
errno.EOWNERDEAD		= 130; /* Owner died */
errno.ENOTRECOVERABLE	= 131; /* State not recoverable */
errno.ERFKILL			= 132; /* Operation not possible due to RF-kill */
errno.EHWPOISON			= 133; /* Memory page has hardware error */

errno.EWOULDBLOCK		= errno.EAGAIN; /* Operation would block */
errno.EDEADLOCK			= errno.EDEADLK;

return errno;
