#!/bin/bash

if [ ! -z "$(git status --porcelain)" ]
then
	echo "Working copy is not clean. Refusing to continue"
	exit 1
fi

if [ "$(git br --show-current)" != "master" ]
then
	echo "Not in master branch. Refusing to continue"
	exit 1
fi

echo ==== Building and passing CI to check validity...
if ! make ci docs
then
	echo "Checks failed. Refusing to continue"
	exit 1
fi

echo Latest 4 tags are:
echo
git tag --sort=-committerdate | head -4
echo 
echo -n "Enter desired new version: "
read VERSION

echo New version will be: $VERSION
echo -n "Confirm (y/N)? "
read CONFIRM

if [ "$CONFIRM" != "y" ]
then 
	exit 1
fi

echo ==== Patching src/joshi/joshi.c version number...
sed -i "s/^#define VERSION .*$/#define VERSION \"$VERSION\"/" src/joshi/joshi.c
git add src/joshi/joshi.c

echo ==== Creating version commit...
git commit -m "chore: prepare version $VERSION"
git push

echo ==== Tagging...
git tag "$VERSION"

echo ==== Pushing tags...
git push --tags

echo ==== Rebasing stable on top of master...
git co stable
git rebase master

echo ==== Pushing stable...
git push

echo ==== Back to master...
git co master

echo ==== Installing to local system...
echo -n "Do you want to install to /usr/local (y/N)? "
read CONFIRM

if [ "$CONFIRM" == "y" ]
then 
	sudo PREFIX=/usr/local make install
fi

echo ==== Patching src/joshi/joshi.c after release...
sed -i "s/^#define VERSION .*$/#define VERSION \"$VERSION-next\"/" src/joshi/joshi.c
git add src/joshi/joshi.c
git commit -m "chore: update joshi.c with snapshot version"
git push
